core/urls.py
# Our imports
from . import views

# Django's imports
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.IndexView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('auth/', include('soninha.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('pong/', include('pong.urls')),
    path('stats/', include('stats.urls')),
    path('blockchain/', include('blockchain.urls')),
	path('search-user/', views.SearchUserView.as_view(), name='search_user'),
	path('friends-list/', views.FriendListView.as_view(), name='friends-list'),
    path('create-friendship/', views.CreateFriendshipView.as_view(), name='create-friendship'),
    path('accept-friendship/', views.AcceptFriendshipView.as_view(), name='accept-friendship'),
	path('check-friendship-status/', views.CheckFriendshipStatusView.as_view(), name='check-friendship-status'),
	path('cancel-friend-request/', views.CancelFriendRequestView.as_view(), name='cancel-friend-request'),
	path('remove-friend/', views.RemoveFriendView.as_view(), name='remove-friend'),
	path('get-user-info/<int:friend_id>/', views.GetUserInfoView.as_view(), name='get_user_info'),
	path('get-friends/', views.GetFriendsView.as_view(), name='get-friends'),
	path('update-last-seen/', views.UpdateLastSeenView.as_view(), name='update-last-seen'),
	path('matches-history-container/<int:friend_id>/', views.GetUserMatchesView.as_view(), name='matches-history-container'),
]

# # Add the media URL pattern only during development
# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # this isn't ideal but oh well what can one do

pong/urls.py
"""URLs for the pong app."""
from django.urls import path
from .views import MatchView, TournamentMatchView

app_name = "pong" # pylint: disable=invalid-name
urlpatterns = [
    path('match', MatchView.as_view(), name='match'),
    path('tournament_match', TournamentMatchView.as_view(), name='tournament_match'),
    path('match/<int:match_id>', MatchView.as_view(), name='match_id'),
]

templates/lobby/components/play-button.html
<svg id={{ play_button_id }} class="mb-2" xmlns="http://www.w3.org/2000/svg" width="138" height="138" viewBox="0 0 138 138" fill="none">
	<circle cx="69" cy="69" r="69" fill="#2C2626"/>
	<g filter="url(#{{ filter_id }})">
	<circle cx="69" cy="68" r="59" fill="#AF1119"/>
	</g>
	<circle id={{ red_circle_id }} cx="69" cy="58" r="58" fill="#AF1119"/>
	<defs>
	<filter id={{ filter_id }} x="10" y="5" width="118" height="122" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
	<feFlood flood-opacity="0" result="BackgroundImageFix"/>
	<feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape"/>
	<feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha"/>
	<feMorphology radius="4" operator="erode" in="SourceAlpha" result="effect1_innerShadow_2976_3736"/>
	<feOffset dy="-7"/>
	<feComposite in2="hardAlpha" operator="arithmetic" k2="-1" k3="1"/>
	<feColorMatrix type="matrix" values="0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0.25 0"/>
	<feBlend mode="normal" in2="shape" result="effect1_innerShadow_2976_3736"/>
	</filter>
	</defs>
</svg>

templates/lobby/components/single-match-modal.html
{% load i18n %}

<div class="modal fade" id="singleMatchModal" tabindex="-1" aria-labelledby="singleMatchModalLabel" aria-hidden="true" data-bs-theme="dark">
  <div class="modal-dialog modal-xl">
    <div id="smModalContent" class="modal-content">
      <div class="modal-header border-0">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <form id="singleMatchForm" action="{% url "pong:match" %}" method="POST">
        {% csrf_token %}
        <div class="modal-body text-white pt-0">
          <h1 class="ms-3 mb-5 w-100 text-center">{% translate "SINGLE MATCH" %}</h1>
          <div class="d-flex justify-content-evenly">
            <div class="d-flex flex-column align-items-center">
              <h3 class="settingName">{% translate "GAME MODE" %}</h3>
              <div class="d-flex flex-column align-items-start">
                <div class="form-check">
                  <input class="form-check-input" type="radio" name="gameTypeDefault" id="coopRadio" value="co-op" checked />
                  <label class="form-check-label" for="coopRadio">{% translate "CO-OP" %}</label>
                </div>
                <div class="form-check">
                  <input class="form-check-input" type="radio" name="gameTypeDefault" id="classicRadio" value="classic" />
                  <label class="form-check-label" for="classicRadio">{% translate "CLASSIC" %}</label>
                </div>
              </div>
            </div>
            <div class="d-flex flex-column align-items-center">
              <h3 class="settingName">{% translate "PLAYER" %}</h3>
              <div class="d-flex flex-column align-items-start">
                <div class="form-check">
                  <input class="form-check-input" type="radio" name="playerDefault" id="twoPlayersRadio" value="2" checked />
                  <label class="form-check-label" for="twoPlayersRadio">{% translate "TWO" %}</label>
                </div>
                <div class="form-check">
                  <input class="form-check-input" type="radio" name="playerDefault" id="smFourPlayersRadio" value="4" />
                  <label class="form-check-label" for="smFourPlayersRadio">{% translate "FOUR" %}</label>
                </div>
              </div>
            </div>
            <div class="d-flex flex-column align-items-center">
              <h3 class="settingName">{% translate "MAP" %}</h3>
              <div class="d-flex flex-column align-items-start">
                <div class="form-check">
                  <input class="form-check-input" type="radio" name="mapDefault" id="smMap1Radio" value="map1" checked />
                  <label class="form-check-label" for="smMap1Radio">{% translate "MAP 1" %}</label>
                </div>
                <div class="form-check">
                  <input class="form-check-input" type="radio" name="mapDefault" id="smMap2Radio" value="map2" />
                  <label class="form-check-label" for="smMap2Radio">{% translate "MAP 2" %}</label>
                </div>
              </div>
            </div>
          </div>
          <div id="playerInputDiv" class="container-fluid my-5">
            <div class="row row-cols-2">
              <div class="col">
                <input type="text" class="form-control" id="firstPlayer" placeholder={{user_login}} disabled/>
                <input type="hidden" name="player1Name" value={{user_login}}>
              </div>
              <div class="col">
                <input type="text" class="form-control" id="secondPlayer" name="player2Name" placeholder="Player 2"/>
              </div>
            </div>
            <div id="player3And4Div" class="row row-cols-2 visually-hidden mt-3">
              <div class="col">
                <input type="text" class="form-control" id="thirdPlayer" name="player3Name" placeholder="Player 3"/>
              </div>
              <div class="col">
                <input type="text" class="form-control" id="fourthPlayer" name="player4Name" placeholder="Player 4"/>
              </div>
            </div>
          </div>
          <button type="submit" id="smPlayButtonDiv" class="btn d-flex flex-column w-100 align-items-center">
            {% with play_button_id="smPlayButtonSvg" red_circle_id="smRedCircle" filter_id="smFilter" %}
              {% include 'lobby/components/play-button.html' %}
            {% endwith %}
          </button>
        </div>
      </form>
    </div>
  </div>
</div>

templates/lobby/components/tournament-modal.html
{% load i18n %}

<div class="modal fade" id="tournamentModal" tabindex="-1" aria-labelledby="tournamentModalLabel" aria-hidden="true" data-bs-theme="dark">
  <div class="modal-dialog modal-xl">
    <div id="tModalContent" class="modal-content">
      <div class="modal-header border-0">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <form id="tournamentForm" action="{% url "pong:match" %}" method="POST">
        {% csrf_token %}
        <div class="modal-body text-white pt-0">
          <h1 class="ms-3 mb-5 w-100 text-center">{% translate "TOURNAMENT" %}</h1>
          <div class="d-flex justify-content-evenly">
            <div class="d-flex flex-column align-items-center">
              <h3 class="settingName">{% translate "GAME MODE" %}</h3>
              <div class="d-flex flex-column align-items-start">
                <div class="form-check">
                  <input class="form-check-input" type="radio" name="gameTypeDefault" id="classicRadio" value="classic" checked />
                  <label class="form-check-label" for="classicRadio">{% translate "CLASSIC" %}</label>
                </div>
                {% comment %} NOT IMPLEMENTED FOR THE TIME BEING {% endcomment %}
                <div class="form-check d-none">
                  <input class="form-check-input" type="radio" name="gameTypeDefault" id="coopRadio" value="co-op" hidden/>
                  <label class="form-check-label" for="coopRadio">{% translate "CO-OP" %}</label>
                </div>
              </div>
            </div>
            <div class="d-flex flex-column align-items-center">
              <h3 class="settingName">{% translate "PLAYER" %}</h3>
              <div class="d-flex flex-column align-items-start">
                <div class="form-check">
                  <input class="form-check-input" type="radio" name="playerDefault" id="tFourPlayersRadio" value="4" checked />
                  <label class="form-check-label" for="tFourPlayersRadio">{% translate "FOUR" %}</label>
                </div>
                <div class="form-check">
                  <input class="form-check-input" type="radio" name="playerDefault" id="eightPlayersRadio" value="8" />
                  <label class="form-check-label" for="eightPlayersRadio">{% translate "EIGHT" %}</label>
                </div>
              </div>
            </div>
            <div class="d-flex flex-column align-items-center">
              <h3 class="settingName">{% translate "MAP" %}</h3>
              <div class="d-flex flex-column align-items-start">
                <div class="form-check">
                  <input class="form-check-input" type="radio" name="mapDefault" id="tMap1Radio" value="map1" checked />
                  <label class="form-check-label" for="tMap1Radio">{% translate "MAP 1" %}</label>
                </div>
                <div class="form-check">
                  <input class="form-check-input" type="radio" name="mapDefault" id="tMap2Radio" value="map2" />
                  <label class="form-check-label" for="tMap2Radio">{% translate "MAP 2" %}</label>
                </div>
              </div>
            </div>
          </div>
          <div id="playerInputDiv" class="container-fluid my-5">
            <div class="row row-cols-2">
              <div class="col">
                <input type="text" class="form-control" id="firstPlayer" placeholder={{user_login}} disabled/>
                <input type="hidden" name="player1Name" value={{user_login}}>
              </div>
              <div class="col">
                <input type="text" class="form-control" id="secondPlayer" name="player2Name" placeholder="Player 2"/>
              </div>
            </div>
            <div id="player3And4Div" class="row row-cols-2 mt-3">
              <div class="col">
                <input type="text" class="form-control" id="thirdPlayer" name="player3Name" placeholder="Player 3"/>
              </div>
              <div class="col">
                <input type="text" class="form-control" id="fourthPlayer" name="player4Name" placeholder="Player 4"/>
              </div>
            </div>
            <div id="player5And6Div" class="row row-cols-2 visually-hidden mt-3">
              <div class="col">
                <input type="text" class="form-control" id="fifthPlayer" name="player5Name" placeholder="Player 5"/>
              </div>
              <div class="col">
                <input type="text" class="form-control" id="sixthPlayer" name="player6Name" placeholder="Player 6"/>
              </div>
            </div>
            <div id="player7And8Div" class="row row-cols-2 visually-hidden mt-3">
              <div class="col">
                <input type="text" class="form-control" id="seventhPlayer" name="player7Name" placeholder="Player 7"/>
              </div>
              <div class="col">
                <input type="text" class="form-control" id="eighthPlayer" name="player8Name" placeholder="Player 8"/>
              </div>
            </div>
          </div>
          </div>
          <button type="submit" id="tPlayButtonDiv" class="btn d-flex flex-column w-100 align-items-center">
            {% with play_button_id="tPlayButtonSvg" red_circle_id="tRedCircle" filter_id="tFilter" %}
              {% include 'lobby/components/play-button.html' %}
            {% endwith %}
          </button>
        </div>
      </form>
    </div>
  </div>
</div>