core/urls.py
# Our imports
from . import views

# Django's imports
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.IndexView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('auth/', include('soninha.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('pong/', include('pong.urls')),
    path('stats/', include('stats.urls')),
    path('blockchain/', include('blockchain.urls')),
	path('search-user/', views.SearchUserView.as_view(), name='search_user'),
	path('friends-list/', views.FriendListView.as_view(), name='friends-list'),
    path('create-friendship/', views.CreateFriendshipView.as_view(), name='create-friendship'),
    path('accept-friendship/', views.AcceptFriendshipView.as_view(), name='accept-friendship'),
	path('check-friendship-status/', views.CheckFriendshipStatusView.as_view(), name='check-friendship-status'),
	path('cancel-friend-request/', views.CancelFriendRequestView.as_view(), name='cancel-friend-request'),
	path('remove-friend/', views.RemoveFriendView.as_view(), name='remove-friend'),
	path('get-user-info/<int:friend_id>/', views.GetUserInfoView.as_view(), name='get_user_info'),
	path('get-friends/', views.GetFriendsView.as_view(), name='get-friends'),
	path('update-last-seen/', views.UpdateLastSeenView.as_view(), name='update-last-seen'),
	path('matches-history-container/<int:friend_id>/', views.GetUserMatchesView.as_view(), name='matches-history-container'),
]

# # Add the media URL pattern only during development
# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # this isn't ideal but oh well what can one do

soninha/urls.py
"""URLs for the soninha app."""
from django.urls import path
from . import views

app_name = 'soninha'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('user/profile-picture', views.ProfilePictureView.as_view(), name='profile_picture'),
    path('user/display-name', views.DisplayNameView.as_view(), name='display_name'),
    path('user/display-name/<str:login_intra>', views.DisplayNameView.as_view(), name='login_intra'),
]

soninha/models.py
"""Models for the soninha app."""
from django.utils import timezone
from django.db import models


class User(models.Model):
    """Model for a user."""

    login_intra = models.CharField(max_length=20)
    display_name = models.CharField(max_length=40)
    intra_cdn_profile_picture_url = models.CharField(max_length=200, null=True)
    profile_picture = models.ImageField(upload_to='profile_pictures/', null=True, blank=True)
    last_seen = models.DateTimeField(default=timezone.now)
    
    def update_last_seen(self):
        self.last_seen = timezone.now()
        self.save(update_fields=['last_seen'])
    def __str__(self):
        return f"I am user [{self.id}] - {self.display_name}"


class Achievements(models.Model):
    """Model for achievements."""

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ball_distance = models.IntegerField(default=0)
    friends_count = models.IntegerField(default=0)
    hours_played = models.IntegerField(default=0)
    matches_classic = models.IntegerField(default=0)
    matches_coop = models.IntegerField(default=0)
    matches_won = models.IntegerField(default=0)

    def __str__(self):
        return f"I am user [{self.user.login_intra}]'s achievements"

soninha/views.py
"""Views for the soninha app."""

# Python Std Libs
from http import HTTPStatus
import json
import os
import requests
import uuid

# Our imports
from soninha.models import User, Achievements
from stats.models import UserStats

# Django's imports
from django.conf import settings
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views import View


class LoginView(View):
    """
    This view is invoked by the intra API after the user has been authenticated.
    It should receive a code from the intra API.
    This code must then be exchanged by a valid access token, which represents the user's authorization for our application to retrieve their information in the intra API.
    """

    def _get_token(self, code):
        """Returns the intra token."""

        intra_endpoint = os.getenv('INTRA_ENDPOINT')
        uid = os.getenv('INTRA_UID')
        secret = os.getenv('INTRA_SECRET')
        redirect_uri = os.getenv('TRANSCENDENCE_IP')
        protocol = os.getenv('TRANSCENDENCE_PROTOCOL')

        url_parameters = "?grant_type=authorization_code&client_id=" + \
            uid + "&client_secret=" + secret + "&code=" + code + \
            "&redirect_uri=" + protocol + "%3A%2F%2F" + redirect_uri + "%3A8000%2Fauth%2Flogin%2F"
        tokenJson = json.loads(requests.post(
            intra_endpoint + '/oauth/token' + url_parameters).content)
        if "access_token" in tokenJson.keys():
            return tokenJson["access_token"]
        return ""

    def get(self,  request, *args, **kwargs):
        """Get method."""

        # Exchange code by authorization token
        # (The user grants permission for our application to retrieve their information)
        code = request.GET.get('code', '')
        token = self._get_token(code)

        if not token:
            return HttpResponse("Couldn't get intra token", status=500)

        # Make new call to intra's API to retrieve user's information
        bearer = "Bearer " + token
        cadet_api = os.getenv('INTRA_ENDPOINT') + os.getenv('CADET_API')
        response = requests.get(
            cadet_api, headers={
                'Authorization': bearer
            }, timeout=5
        )

        # Get user information from response
        parsedResponse = json.loads(response.content)
        login_intra = parsedResponse["login"]
        pfp_intra = parsedResponse["image"]["versions"]["medium"]
        if not pfp_intra:
            pfp_intra = "/static/images/default_user_image.svg"

        # Create new user entry in our database, or just retrieves it if they've logged in before
        user, is_new_entry = User.objects.get_or_create(login_intra=login_intra)
        if (is_new_entry):
            user.display_name = login_intra
            user.intra_cdn_profile_picture_url = pfp_intra
            user.save()
        # Create new achievement entry for user in our database
        achievements, is_new_entry = Achievements.objects.get_or_create(user=user)
        # Create new stats entry for user in our database
        user_stats, is_new_entry = UserStats.objects.get_or_create(user=user)

        # Register user as logged in in session
        request.session["user_id"] = user.id

        return redirect('/')  # This will return the html


class LogoutView(View):
    """Logout view."""

    def get(self, request, *args, **kwargs):
        """Get method."""
        request.session["user_id"] = ""
        return HttpResponse('')


class ProfilePictureView(View):
    def post(self, request, *args, **kwargs):
        uploaded_file = request.FILES.get('profilePicture')
        if not uploaded_file:
            return render(request=request, template_name='components/errors/empty_profile_picture_form.html', status=HTTPStatus.BAD_REQUEST)

        user = get_object_or_404(User, pk=request.session.get("user_id"))

        # Delete the old profile picture file if it exists
        if user.profile_picture:
            old_file_path = os.path.join(settings.MEDIA_ROOT, str(user.profile_picture))
            if os.path.exists(old_file_path):
                os.remove(old_file_path)

        # Generate a unique filename for the uploaded file
        filename = f"{uuid.uuid4().hex}{os.path.splitext(uploaded_file.name)[1]}"

        # Define the directory where you want to save the uploaded files
        upload_dir = os.path.join(settings.MEDIA_ROOT, 'profile_pictures')
        if not os.path.exists(upload_dir):
            os.makedirs(upload_dir)
        
        # Construct the file path with the unique filename
        file_path = os.path.join(upload_dir, filename)

        # Save the file to the filesystem
        with open(file_path, 'wb') as destination:
            for chunk in uploaded_file.chunks():
                destination.write(chunk)

        # Update the user's profile picture attribute with the file path
        user.profile_picture = os.path.relpath(file_path, settings.MEDIA_ROOT)
        user.save()

        return JsonResponse({"new_pfp_url": user.profile_picture.url}, status=HTTPStatus.OK)

class DisplayNameView(View):
    def get(self, request, *args, **kwargs):
        login_intra = kwargs["login_intra"]
        user = User.objects.get(login_intra=login_intra)
        return JsonResponse({"display_name": user.display_name})

        
    def post(self, request, *args, **kwargs):
        new_display_name = request.POST.get("display-name")

        if not new_display_name:
            return render(request=request, template_name='components/errors/empty_display_name_form.html', status=HTTPStatus.BAD_REQUEST)

        user = get_object_or_404(User, pk=request.session.get("user_id"))

        # Update the user's profile picture attribute with the file path
        user.display_name = new_display_name
        user.save()

        return JsonResponse({"new_display_name": user.display_name}, status=HTTPStatus.OK)

templates/soninha/partials/achievements-segment.html
{% load static i18n %}

<h3>{% translate "ACHIEVEMENTS" %}</h3>
<!-- First row of images -->
<div class="d-flex mt-3">
  <!-- Ball Distance -->
  <img class="achievementImage me-3" width="80" height="80" src="{% static ball_distance.src %}" alt="{{ ball_distance.alt_text }}" title="{{ ball_distance.title }}">
  <!-- Friends Count -->
  <img class="achievementImage me-3" width="80" height="80" src="{% static friends_count.src %}" alt="{{ friends_count.alt_text }}" title="{{ friends_count.title }}">
  <!-- Hours Played -->
  <img class="achievementImage me-3" width="80" height="80" src="{% static hours_played.src %}" alt="{{ hours_played.alt_text }}" title="{{ hours_played.title }}">
</div>

<!-- Second row of images -->
<div class="d-flex mt-3">
  <!-- Classic -->
  <img class="achievementImage me-3" width="80" height="80" src="{% static matches_classic.src %}" alt="{{ matches_classic.alt_text }}" title="{{ matches_classic.title }}">
  <!-- Co-op Count -->
  <img class="achievementImage me-3" width="80" height="80" src="{% static matches_coop.src %}" alt="{{ matches_coop.alt_text }}" title="{{ matches_coop.title }}">
  <!-- Win Played -->
  <img class="achievementImage me-3" width="80" height="80" src="{% static matches_won.src %}" alt="{{ matches_won.alt_text }}" title="{{ matches_won.title }}">
</div>

templates/soninha/partials/display-name.html
<div id="userDisplayName" class="d-flex justify-content-start align-items-center mb-0">
  <h1><span>{{ user_display_name }}</span></h1>
  <button type="button" aria-label="Edit user display name" class="ms-3"><i class="fa fa-pencil-square" aria-hidden="true"></i></button>
</div>

<form id="userDisplayNameForm"
  class="d-none d-flex justify-content-start align-items-center"
  method="post"
  action="{% url "soninha:display_name" %}"
>
  {% csrf_token %}
  <input id="displayNameEditionInput" type="text" name="display-name" value="{{ user_display_name }}" maxlength="20" required />
  <button type="submit" aria-label="Edit user display name" class="ms-3"><i class="fa fa-pencil-square" aria-hidden="true"></i></button>
</form>

templates/soninha/partials/friends-segment.html
{% load static i18n %}

<h3>{% translate "MATES ALONG THE WAY" %}</h3>
<!-- Flex container for friends images and the plus sign -->
<div class="d-flex mt-3 col-8 md-4">
    <!-- Div for friends images -->
    <div id="friendsContainer">
        <!-- Friends will be added here by JS -->
    </div>
    <!-- Plus sign to add more friends, wrapped in a span to align it with images -->
    <h1 id="addSign" class="align-self-center ms-2">+</h1>
</div>

<script type="module" src="{% static 'js/mates-along.js' %}" defer></script>

templates/soninha/partials/profile-picture-edition-form.html
{% load i18n %}

<form id="profilePictureEditionForm"
  method="post"
  action="{% url 'soninha:profile_picture' %}"
  enctype="multipart/form-data"
>
  {% csrf_token %}
  <div class="mb-3">
    <input id="profilePicEditionInput" name="profilePicture" class="form-control" type="file" id="formFile" accept="image/jpeg, image/png">
  </div>
  <div class="modal-footer">
    <button type="submit" class="btn btn-primary">{% translate "Upload Picture" %}</button>
  </div>
</form>

templates/soninha/partials/profile-picture-edition-modal.html
{% load i18n %}

<div class="modal fade" id="profilePictureEditionModal" tabindex="-1" role="dialog" aria-labelledby="profilePictureEditionModalLabel" aria-hidden="true" data-bs-theme="dark">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header border-0">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>

      <div class="modal-body">
        <!-- Heading -->
        <h4 class="text-center mb-3">{% translate "CHANGE PROFILE PICTURE" %}</h4>

        <!-- Current Profile Picture -->
        <div class="container mb-3 ">
            <div class="row justify-content-center">
                <div class="col-md-6">
                    <div  id="currentProfilePicture" class="roundedSquareImage centered-div" style="background-image: url('{{ user_image }}');"></div>
                </div>
            </div>
        </div>

        <!-- Form -->
        {% include "soninha/partials/profile-picture-edition-form.html" %}
      </div>

    </div>
  </div>
</div>

templates/soninha/partials/profile-picture.html
<div id="profilePicture" class="roundedSquareImage" style="background-image: url('{{ user_image }}');">
  <!-- Button to trigger modal -->
  <button class="btn" data-bs-toggle="modal" data-bs-target="#profilePictureEditionModal"><i class="fa fa-pencil"></i></button>
</div>

templates/soninha/partials/user-stats.html
{% load i18n %}

<div id="userStatsDiv" class="d-flex mt-3">
  <h4 class="ms-3"  title="{% translate 'Team ball hits record' %}">🙌 {{ ball_hits_record }}</h4>
  <h4 class="ms-3"  title="{% translate 'Distance traveled with a companion' %}">📍 {{ cumulative_ball_distance }}</h4>
  <h4 class="ms-3"  title="{% translate 'Total hours played' %}">🕰️ {{ total_hours_played }}</h4>
  <h4 class="ms-3"  title="{% translate 'Companions encountered' %}">👯 {{ unique_companions_encountered }}</h4>
  <h4 class="ms-3"  title="{% translate 'Classic games won' %}">🏆 {{ wins }}</h4>
  <h4 class="ms-3"  title="{% translate 'Classic games lost' %}">😞 {{ losses }}</h4>
</div>